language: node_js
node_js:
- '6'
branches:
  only:
  - blog-source
before_install:
- npm install -g hexo
- npm install -g hexo-cli
before_script:
- wget https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb
- sudo dpkg -i pandoc-1.19.2.1-1-amd64.deb
install:
- npm install
script:
- hexo clean
- hexo generate
after_script:
- cd public
- git init
- git config --global user.name 'GeekaholicLin'
- git config --global user.email 'geekaholiclin@gmail.com'
- hexo deploy
- git add .
- git commit -m"Update Site By Travis"
- git push --force "https://${GITHUB_TOKEN}@${GITHUB_REPO}" master:master
- git push --force "https://Geekaholic:${CODING_TOKEN}@${CODING_REPO}" master:master

env:
  global:
  - GITHUB_REPO: github.com/GeekaholicLin/geekaholiclin.github.io.git
  - CODING_REPO: git.coding.net/Geekaholic/Geekaholic.git
