language: node_js
node_js:
- '6'
branches:
  only:
  - blog-source
before_install:
- openssl aes-256-cbc -K $encrypted_9da365035dd8_key -iv $encrypted_9da365035dd8_iv -in .travis/travis-hexo_rsa.enc -out ~/.ssh/travis-hexo_rsa -d
#- openssl aes-256-cbc -K $encrypted_d16ac2c469ba_key -iv $encrypted_d16ac2c469ba_iv
  #-in .travis/travis-hexo_rsa.enc -out ~/.ssh/travis-hexo_rsa -d
- chmod 600 ~/.ssh/travis-hexo_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/travis-hexo_rsa
- cp .travis/ssh_config ~/.ssh/config
- npm install -g hexo
- npm install -g hexo-cli
before_script:
- git config --global user.name 'GeekaholicLin'
- git config --global user.email 'geekaholiclin@gmail.com'
- wget https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb
- sudo dpkg -i pandoc-1.19.2.1-1-amd64.deb
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- hexo deploy
env:
  global:
  - GITHUB_REPO: github.com/GeekaholicLin/geekaholiclin.github.io.git
  - CODING_REPO: git.coding.net/Geekaholic/Geekaholic.git
