language: node_js
branches:
  only:
    - blog-source #源码分支名称
before_install:
  - npm install -g hexo
  - npm install -g hexo-cli
before_script:
  - git config --global user.name 'GeekaholicLin'
  - git config --global user.email 'geekaholiclin@gmail.com'

install:
  - npm install
script:
  - hexo clean
  - hexo generate
after_success:
  - cd ./public
  - git init
  - git add .
  - git commit -m "update blog using Travis"
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GITHUB_REPO}" master:master
  - git push --force --quiet "https://${CODING_TOKEN}@${CODING_REPO}" master:master
env:
  global:
    - GITHUB_REPO: github.com/GeekaholicLin/geekaholiclin.github.io.git
    - CODING_REPO: git.coding.net/Geekaholic/Geekaholic.git